upstream php {
    server php:9000;
}

server {
    root   /usr/share/nginx/wordpress;
    index  index.php index.html index.htm;
    client_max_body_size 16M;

    # Sadly it seems I need to start doing this...
    include conf.d/includes/ai.filter.conf;
    include conf.d/includes/deny_ip.conf;

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location ~ /\. { deny all; }    
    location ~* /(?:uploads|files)/.*\.php$ { deny all; }
    location = /xmlrpc.php { deny all; }

    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt { log_not_found off; access_log off; allow all; }

    location ~* \.(css|gif|ico|jpeg|jpg|js|png)$ {
        expires max;
        log_not_found off;
    }

    location ~ ^/.+\.php(/|$) {
        include fastcgi_params;

	fastcgi_pass php;
	fastcgi_keep_conn on;
	fastcgi_intercept_errors on;

	# This path MUST match the path to the Wordpress scripts
	# visible to the PHP container

	fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
    }

    listen 80;
    listen [::]:80;
    server_name wordpress;
}

